### ISSUE TITLE
Negative "Not Completed" counts

### ISSUE THREAD

**Issue by sfinkel-hi** [Twoscope/moodle-report_completionoverview#2] opened 2018-10-23 17:46 UTC
While testing, I needed to delete and re-create a couple test user accounts and now the course completion counts are off. 

![coursecompletionoverview](https://user-images.githubusercontent.com/40212316/47379746-ff477600-d6b8-11e8-860f-ca576d946562.JPG)

Any ideas on how to resolve this? Thanks!

**Comment by Jim-Twoscope** [comment] 2018-10-23 18:34
Hi, thanks for getting in touch 
This is a strange one and not something I encountered while testing. 
When I get the chance I'll investigate for you and see if I can replicate the problem. 
My first thought is that the SQL query is calculating the total student count on the course as 0 correctly but then including the deleted accounts in the total of non completers which is then leading to a negative value. 

Having said this, I think moodle should unenrol a learner when they are deleted and the plugin only checks on enrolled learners.

Is the enrolment info/count correct on Moodle for these courses?

The only other thing I can think of is completion data in moodle is calculated after a specific cron job runs, it doesn't update automatically. 

Perhaps making sure the cron job is running correctly may solve the issue 

Hope this makes sense 

Jim

**Comment by sfinkel-hi** [comment] 2018-10-23 19:08
Thanks for your quick response! 

I also thought that Moodle would unenroll a student when deleting the user account. However, in order to not have a million test user emails,  I did re-create the account with the same email. 

I have the cron set up to run every 5 minutes using the cli. I don't seem to notice any other issues with the moodle instance with this set up in general. Is there a different cron job for completion data other than the admin/cli/cron.php? 

Unfortunately, the Course Enrollment and Completed numbers are off as well :(
I have uninstalled and reinstalled the plugin too. For now, I will uninstall it. 

thanks again for your help!!

**Comment by Jim-Twoscope** [comment] 2018-10-23 19:55
No problem Sarah, we'll get to the bottom of it.

I don't think using the same email address would be an issue,  the recreated account should be seen as a new student 

The scheduled task that updates the completion data is part of the admin/click/cron job but it's set to run at specific intervals, not every time the main cron runs 

I don't think this would affect the enrolment count though as that doesn't look at the completion tables in the database at all

The fact that the enrolment count is wrong too makes this very confusing as that just does a simple count on the number of students 'live' on the course (nothing to do with completion)

It seems somewhere down the line there's some confusion in the data between the deleted accounts and the recreated ones

Are you using moodle 3.3 or 3.4?

Jim

**Comment by sfinkel-hi** [comment] 2018-10-23 21:56
Moodle is 3.4.

When I was having issues the first time, I had another plugin installed to help with custom enrollments (Course completed enrollment) but that was only active on the 1st and last course, not the courses with the negative enrollment numbers.

**Comment by Jim-Twoscope** [comment] 2018-10-24 06:15
Hi Sarah

Thanks for the info. When I get the chance I'll see if I can replicate the issue but I suspect the issue stems from the other enrolment plugin you mention, which has somehow skewed the course enrolment numbers 

If the enrolment total is incorrect the other totals in my plugin will be affected as completion totals are calculated from the enrolment count 

I notice that you've contacted the author of the enrolment plugin and mention using it on 8 courses. It also seems to have had an impact on the certificate plugin on your course 

It might be worth trying my plugin again on a course and with users that have had no involvement with the custom enrolment plugin 

Hope this makes sense 

Jim

**Comment by Jim-Twoscope** [comment] 2018-10-28 14:11
Hi Sarah, hope all is good

I've conducted some tests and unfortunately (fortunately!) can't reproduce the error/problem your seeing.

I set up a simple test course and assigned learners to it. The course completion overview plugin reported the correct number of enrolments and completions.

I then deleted some users and tested the plugin enrolment and completion figures. Once again these were correct. The report updated by simply refreshing the page and didn't require cron to run.

I then recreated some of the learners using the same email addresses and once again my plugin showed the correct totals for enrolment and completion.

I can only assume that the custom enrolment plugin you installed caused some kind of impact on the figures reported by my plugin. I'm not sure how this enrolment plugin works or which Moodle database tables it uses. It may even use it's own tables but somehow it seems to have affected the calculations made by my plugin.

I'm afraid, I don't think there's much more I can do to help here as I don't think the issue lies with my plugin.

If you try my plugin again in isolation of the custom enrolment plugin you used I think you'll find it all works as it should.

Of course, if this isn't the case you can always get back in touch.

For now though, I'd like to close this issue if it's ok with you?

Jim

**Closed as completed** 2018-10-31 20:16 UTC
